name: Build Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'python' ]
        # Learn more...
    container:
      image: node
    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          pip install -r requirements.txt

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t back .
