name: Build Docker image

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'python' ]
        # Learn more...
    container:
      image: python 
    steps:
      - uses: actions/checkout@v3
      - name: Install & Tests
        run: |
          pip install poetry && poetry install

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -t back .
